backend:
  name: git-gateway
  branch: dev

media_folder: "site/static/_images" # Folder where user uploaded files should go
public_folder: "/"

collections: # A list of collections the CMS should be able to edit
  - name: "resources/blog" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Blog" # Used in the UI, ie.: "New Post"
    folder: "site/content/resources/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Category", name: "category", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Intro Blurb", name: "description", widget: "text"}
      - {label: "Images", name: "images", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}